### ISSUE TITLE
Running thread is preventing app exit

### ISSUE THREAD

**Issue by Sija** [amplitude/Amplitude-Python#19]
## Current Behavior

I've noticed that using this library breaks gunicorn [auto-reload](https://docs.gunicorn.org/en/stable/settings.html#reload) functionality.
Our CLI scripts started to linger on exit as well.

Below is the output from our flask app:

```
[2022-04-21 17:39:21 +0000] [64] [INFO] Worker reloading: /app/foo.py 
[2022-04-21 17:39:21 +0000] [66] [INFO] Worker exiting (pid: 66)
[2022-04-21 17:47:53 +0000] [19] [CRITICAL] WORKER TIMEOUT (pid:66)
Exception ignored in: <module 'threading' from '/usr/local/lib/python3.9/threading.py'>
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/threading.py", line 1470, in _shutdown
    lock.acquire()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/base.py", line 203, in handle_abort
    sys.exit(1)
SystemExit: 1
```

## Expected Behavior

I'd expect that using this library wouldn't interfere with graceful shutdown.

## Steps to Reproduce

```py
# app/foo.py

from flask import Flask
from werkzeug.serving import run_simple
from amplitude import Amplitude

def application(environ, start_response):
    return app(environ, start_response)

app = Flask(__name__)
amplitude = Amplitude("foo")

if __name__ == '__main__':
    run_simple(
        app.config.get("HOST", "0.0.0.0"),
        app.config.get("PORT", 5000),
        application,
        use_reloader=True
    )
```

Run with: `gunicorn --reload --bind 0.0.0.0:5000 foo:application`

## Environment

- SDK Version: 0.2.1
- Python Version: 3.9.12
- OS Info: macOS 12.3.1 / Docker `python:3.9-slim-buster` image

**Comment by bohan-amplitude** [comment]
@Sija , Thank you for your feedback. I'll look into this issue and get back to you ASAP.

**Comment by Sija** [comment]
@bohan-amplitude Great, thanks a bunch! 🙏 btw, after a quick glance, locking in `Workers.buffer_consumer` method _looks_ like a potential culprit, that's just a hunch though.

**Comment by bohan-amplitude** [comment]
Hi @Sija , I tested your code in my local env and reproduced the case. The reload of gunicorn detect file changes and restart the worker. But our client created a consumer thread to check event buffer. This thread didn't stop and caused the restart timeout. There is a shutdown() method that should be called before exit of application. shutdown() method flush the events left in buffer and close the threads out of main thread.

**Comment by Sija** [comment]
@bohan-amplitude I'm aware of this method, but there was no way I couldn't find to hook into gunicorn signaling. Also, I believe the consumer threads shouldn't block, giving possibility of killing them by a parent process.

**Comment by bohan-amplitude** [comment]
I found that there are [server hooks](https://docs.gunicorn.org/en/stable/settings.html#server-hooks) seems can be used for on_reload. I'm not familiar with gunicorn that much. Maybe use signal.signal(signal.SIGINT, handler) to pass a handler that call the shutdown method. I'm also going to research if it's possible to set a signal handler for consumer thread.

**Comment by Sija** [comment]
That's correct, I'm not sure though how I could call the amplitude code inside the worker from the master process without some kind of IPC overkill. `signal.signal` doesn't work either. Moreover I believe that hanging the whole process is a design flaw, and expectations of full control over process exit is not sth you can realistically have.

**Comment by bohan-amplitude** [comment]
Hi @Sija , I did some research and test. A new worker process started after previous work timeout error on my end. It seems that it's safe to ignore this error on test and development env. Our library is not a right place to do signal binding and handling. The recommended way is to call client.shutdown() for application closure/restart.

**Comment by Sija** [comment]
Thing is that the timeout prevents the app from exiting... We cannot wait until the thread timeouts just to exit/reload the app.

**Comment by bohan-amplitude** [comment]
@Sija I updated the logic in worker module. The consumer thread will stop instead of running forever when storage is empty. Please test the version 0.2.2 and let me know if you have any other issue. Thank you.

**Comment by Sija** [comment]
@bohan-amplitude That works great, thanks! 🙏

**Comment by Sija** [comment]
One improvement I can see is setting a graceful exit timeout in case there are events waiting to be flushed.
At the moment they're simply discarded on program exit:

```
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.9/site-packages/amplitude/worker.py", line 75, in 
    self.threads_pool.submit(self.send, events)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 169, in submit
    raise RuntimeError('cannot schedule new futures after '
RuntimeError: cannot schedule new futures after interpreter shutdown
```
