### ISSUE TITLE
Two different `Amplitude` instances send event to the same project

### ISSUE THREAD

**Issue by hurlenko** [amplitude/Amplitude-Python#45]
Consider this sample code:

```python
client_a = Amplitude(PROJECT_A)
client_b = Amplitude(PROJECT_B)

client_a.track(...)  # sends event to PROJECT_B
```

## Expected Behavior
`client_a.track(...)` sends the  event to PROJECT_A

## Current Behavior
`client_a.track(...)` sends the  event to PROJECT_B

## Possible Solution

Don't use mutable defaults in function arguments as they are shared across all class instances:
https://github.com/amplitude/Amplitude-Python/blob/ec790705394ed180079e198099149574a402c614/src/amplitude/client.py#L40

https://github.com/amplitude/Amplitude-Python/blob/ec790705394ed180079e198099149574a402c614/src/amplitude/client.py#L48-L49

Can be replaced with something like:

```python
def __init__(self, api_key: str, configuration: Optional[Config] = None):
    self.configuration = configuration or Config()
```

Possible workaround for now is to specify different config instances explicitly:

```python
client_a = Amplitude(PROJECT_A, configuration=Config())
client_b = Amplitude(PROJECT_B, configuration=Config())
```

Another possible bug with this scenario might be here (didn't check):

https://github.com/amplitude/Amplitude-Python/blob/ec790705394ed180079e198099149574a402c614/src/amplitude/config.py#L58

## Environment
- SDK Version: `amplitude-analytics==1.1.0`
- Python Version: 3.9.16
- OS Info: macOS 13.2

**Comment by Mercy811** [comment]
Hi @hurlenko, thanks for creating this issue. It should be fixed in `1.1.2`. Please upgrade to the latest version.
