### ISSUE TITLE
All event_properties ignored if one key value is "None"

### ISSUE THREAD

**Issue by dxprog** [amplitude/Amplitude-Python#52]
## Expected Behavior
When sending an event via `amplitude.track` with a dictionary of event properties where one value might be `None`, expect that the `None` value is either serialized to `null` or deleted.

## Current Behavior
If any value within a dictionary is `None`, no event properties are sent. I suspect this is also an issue for `user_properties` and `group_properties`, though have not verified. [Per the object validation method](https://github.com/amplitude/Amplitude-Python/blob/main/src/amplitude/event.py#L1266), a `None` value would cause the entire object to fail.

## Possible Solution
Add `None` type to the list of valid values and let the object serialize it to `null`. This can then be filtered out appropriately in charts or addressed in code if it's an incorrect value.

## Steps to Reproduce
```python
okay_event = BaseEvent(
  event_type='test event', 
  user_id='12345',
  event_properties={'requiredProp': 'this is never null', 'optionalProp': 'this is sometimes null'},
)
okay_event.get_event_body()
# {'user_id': '12345', 'event_type': 'test event', 'event_properties': {'requiredProp': 'this is never null', 'optionalProp': 'this is sometimes null'}}

fail_event = BaseEvent(
  event_type='test event', 
  user_id='12345',
  event_properties={'requiredProp': 'this is never null', 'optionalProp': None},
)
fail_event.get_event_body()
# {'user_id': '12345', 'event_type': 'test event'}
```

## Environment
- SDK Version: 1.1.3
- Python Version: 3.11
- OS Info: Ubuntu 20.04

**Comment by sheepsy90** [comment]
I experience the same issue. I also belief that this is incorrect behavior.

**Comment by liuyang1520** [comment]
Hi @dxprog , @sheepsy90 , thanks for reporting this!

It looks like a bug, and I am going to give it a try.

Thanks!

**Comment by liuyang1520** [comment]
The fix has been merged and released in https://pypi.org/project/amplitude-analytics/1.1.4/, PTAL! Closing this issue now. Thanks for supporting Amplitude!
