### ISSUE TITLE
No event when I send int Id

### ISSUE THREAD

**Issue by navff** [amplitude/Amplitude-Python#56]
## Expected Behavior
Amplidue works with integer Id

## Current Behavior
Amplidue don't  works with integer Id

## Steps to Reproduce
1. Send event with int user_id = 99
2. There is no events in panel
3. Send event with user_id = "USER_99"
4. There is event in panel

## Environment
- SDK Version: v1.1.4
- Python Version: 3.12.1
- OS Info: Win11

**Comment by navff** [comment]
https://github.com/rudderlabs/rudder-transformer/issues/127

**Comment by izaaz** [comment]
@navff thank you for reaching out. We expect the min id length to be 5 characters by default. This can be overridden by updating `min_id_length` in the configuration to a lower value.

https://www.docs.developers.amplitude.com/data/sdks/python/#configuration
